
export const SET_RISK_LEVEL = 'SET_RISK_LEVEL';
export const SET_PORTFOLIO_VIEW = 'SET_PORTFOLIO_VIEW';
export const SET_INVESTMENT_AMOUNT = 'SET_INVESTMENT_AMOUNT';
export const SET_INVESTMENT_PERCENTAGE = 'SET_INVESTMENT_PERCENTAGE';